reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
script:
- pod install --project-directory=./Example/
- xcodebuild -workspace 'Example/iShowcase.xcworkspace' -scheme iShowcase -sdk iphonesimulator build
